// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recordprinter.proto

package recordwants

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Config struct {
	LastPrint            int64    `protobuf:"varint,1,opt,name=last_print,json=lastPrint,proto3" json:"last_print,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_64d806c9fbb1e5c8, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetLastPrint() int64 {
	if m != nil {
		return m.LastPrint
	}
	return 0
}

func init() {
	proto.RegisterType((*Config)(nil), "recordwants.Config")
}

func init() { proto.RegisterFile("recordprinter.proto", fileDescriptor_64d806c9fbb1e5c8) }

var fileDescriptor_64d806c9fbb1e5c8 = []byte{
	// 93 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x4a, 0x4d, 0xce,
	0x2f, 0x4a, 0x29, 0x28, 0xca, 0xcc, 0x2b, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x86, 0x08, 0x96, 0x27, 0xe6, 0x95, 0x14, 0x2b, 0xa9, 0x73, 0xb1, 0x39, 0xe7, 0xe7, 0xa5,
	0x65, 0xa6, 0x0b, 0xc9, 0x72, 0x71, 0xe5, 0x24, 0x16, 0x97, 0xc4, 0x83, 0x15, 0x4b, 0x30, 0x2a,
	0x30, 0x6a, 0x30, 0x07, 0x71, 0x82, 0x44, 0x02, 0x40, 0x02, 0x49, 0x6c, 0x60, 0xcd, 0xc6, 0x80,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x93, 0x9a, 0xbd, 0x41, 0x53, 0x00, 0x00, 0x00,
}
