// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        (unknown)
// source: recordprinter.proto

package recordprinter

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastPrint int64 `protobuf:"varint,1,opt,name=last_print,json=lastPrint,proto3" json:"last_print,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recordprinter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_recordprinter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_recordprinter_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetLastPrint() int64 {
	if x != nil {
		return x.LastPrint
	}
	return 0
}

var File_recordprinter_proto protoreflect.FileDescriptor

var file_recordprinter_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x70, 0x72, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x22, 0x27, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1d,
	0x0a, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x42, 0x11, 0x5a,
	0x0f, 0x2e, 0x3b, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_recordprinter_proto_rawDescOnce sync.Once
	file_recordprinter_proto_rawDescData = file_recordprinter_proto_rawDesc
)

func file_recordprinter_proto_rawDescGZIP() []byte {
	file_recordprinter_proto_rawDescOnce.Do(func() {
		file_recordprinter_proto_rawDescData = protoimpl.X.CompressGZIP(file_recordprinter_proto_rawDescData)
	})
	return file_recordprinter_proto_rawDescData
}

var file_recordprinter_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_recordprinter_proto_goTypes = []interface{}{
	(*Config)(nil), // 0: recordprinter.Config
}
var file_recordprinter_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_recordprinter_proto_init() }
func file_recordprinter_proto_init() {
	if File_recordprinter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_recordprinter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_recordprinter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_recordprinter_proto_goTypes,
		DependencyIndexes: file_recordprinter_proto_depIdxs,
		MessageInfos:      file_recordprinter_proto_msgTypes,
	}.Build()
	File_recordprinter_proto = out.File
	file_recordprinter_proto_rawDesc = nil
	file_recordprinter_proto_goTypes = nil
	file_recordprinter_proto_depIdxs = nil
}
